### ISSUE TITLE
Support nightly-2022-02-23 and later

### ISSUE THREAD

**Issue by Enselic** [Enselic/public_items#27]
Nightly CI currently fails: https://github.com/Enselic/public_items/actions/runs/1894448929

We await a new release of rustdoc-types

**Comment by aDotInTheVoid** [comment]
0.7 should fix this. Something like https://github.com/awslabs/smithy-rs/blob/f7e1f0836eb59e29fad668f9b0b3ad682757b5af/tools/api-linter/src/cargo.rs#L78-L96 might be worth doing to verify the version is the same so you can get a nicer error

**Comment by Enselic** [comment]
Yeah, I forgot to `git fetch` in my `rustdoc-types`, so I didn't see that you already took care of this 🤦

**Comment by Enselic** [comment]
Closed by #28
