### ISSUE TITLE
Rename project to `public-api`

### ISSUE THREAD

**Issue by Enselic** [Enselic/public_items#64]
See discussion in https://github.com/Enselic/cargo-public-items/issues/17

But let's wait with renaming `public_items` until at least https://github.com/Enselic/public_items/pull/53 has been merged, because otherwise there will be massive amounts of merge conflicts

**Comment by Enselic** [comment]
@douweschulte FYI, I plan on doing this now while there are no big open PRs, to get it over with. It is better to do it sooner rather than later. As soon as I have done the rename I will also make a v0.9.0 release.

**Comment by douweschulte** [comment]
I agree wholeheartedly.
